### ISSUE TITLE
What service is connecting to fscta65w.com

### ISSUE THREAD

**Issue by Kirembu** [pmahon2016/ddmon#1]
https://github.com/pmahon2016/ddmon/blob/9103f36d85f58f69acbe0e2f897793f746c91b83/old_domain_list.txt#L425

Hi,

I'm seeing a service connecting to the domain fscta65w.com not sure what that domain is supposed to be about... Mind sharing what service is accessing that domain?

**Comment by pmahon2016** [comment]
I saw that and have looked it up - seems to be tied to anti malware ...but every site I searched said it is okay. I left it in just to keep watching it but unfortunately I can't give you anything more.

**Comment by Kirembu** [comment]
> I saw that and have looked it up - seems to be tied to anti malware ...but every site I searched said it is okay. I left it in just to keep watching it but unfortunately I can't give you anything more.

Hi, thanks! Looks like it's ExpressVPN.
It was marked safe but I didn't know what it was.

https://twitter.com/expressvpn/status/1184418057394872321
